---
title: Блог Богдана
baseURL: "/"
googleAnalytics: "UA-162550995-10"
params:
  layout_style: overflow
  palette: green
  header:
    title: Bolik1234
    tagline: Блог Богдана
    profile_img: "/images/sleepy-sandy.jpg"
    bg: dark
    has_nav: true
    has_social: true
  footer:
    content: "&copy; All rights reserved."
    links: []
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
